name: bkwiki_clone
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_neumorphic: ^3.1.0
  get: ^4.6.5
  hexcolor: ^3.0.1
  flutter_iconly: ^1.0.2
  card_swiper: ^2.0.4
  fancy_shimmer_image: ^2.0.2
  page_transition: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
